cypress-io/eslint-plugin-cypress

- README.md
- docs/rules/no-assigning-return-values.md
- index.js
- lib/config/recommended.js
- lib/rules/no-assigning-return-values.js
- package.json
- tests/lib/rules/no-assigning-return-values.js
Adds an opinionated rule as suggested in #4. Tries to help with the ["Assigning Return Values" Best Practice described in the guide](https://docs.cypress.io/guides/references/best-practices.html#Assigning-Return-Values), something that bit me when I was first trying out Cypress.
When writing the rules and the folder layout, I tried to follow the practices described in [the ESLint guide](https://eslint.org/docs/developer-guide/working-with-rules). I also chose `jest` as the test runner but it can be easily switched to Mocha or whatever a maintainer would prefer.
I also updated the readme to instruct on how to add the recommended config, as well as a list of rules and instructions for developing new rules.
Known shortcomings:
* This rule should catch any assignment type (`let`, `const`, …
> Adds a recommended config with new no-assigning-return-values rule

- README.md
- docs/rules/no-unnecessary-waiting.md
- index.js
- lib/config/recommended.js
- lib/rules/no-unnecessary-waiting.js
- tests/lib/rules/no-unnecessary-waiting.js
Based on the [best practice](https://docs.cypress.io/guides/references/best-practices.html#Unnecessary-Waiting) and what I think was originally suggested in #4. Will error if calling `cy.get` with a number literal. Also adds this rule to the default recommended set of this plugin.
Based on #6, will refactor/rebase if any changes are needed there. I can also move the base stuff (set up a recommended config, test tools, etc.) to its own PR if it would be easier.
---
```js
// cypress/.eslintrc.js
module.exports = {
plugins: ['cypress'],
extends: 'plugin:cypress/recommended',
env: {
'cypress/globals': true
}
}
```
```js
// cypress/test.js
describe('something', () => {
it('might do a thing', () => {
cy.visit('/');
cy.wait(1000);
});
});
```
```shell
$ yarn run eslint cypress/test.js …
```
> Add `no-unnecessary-waiting` rule

- index.js
on second thought, we should probably move `chai` onto `Cypress` and deprecate global `window.chai`
> add chai to globals

- index.js
- tests/config.js
Currently the 'cypress/globals' env globals key is made into a copy
of the 'browser' env and changes its contents. Instead, make it a
distinct object.
Add test case that fails if the globals are tampered with on import.
Fixes cypress-io/eslint-plugin-cypress#26
> Avoid mutating eslint browser environment

- tests/lib/rules/require-data-selectors.js
When working on #32, I've seen that the rule name was not the good one.
> chore(wording): fix ruleName of "require-data-selectors" test

- lib/rules/no-unnecessary-waiting.js
- tests/lib/rules/no-unnecessary-waiting.js
This is to handle cases where we have : 
const SLEEP = 500;
cy.wait(SLEEP)
This is still an unnecessary wait and should not be used.
> Added handling for when the wait method is given an Identifier which has a number value

- lib/rules/no-unnecessary-waiting.js
- tests/lib/rules/no-unnecessary-waiting.js
- Closes #35
- Closes #21
```js
// Already throws a lint error
cy.wait(100);
// Now throws a lint error
cy.foo().wait(100);
cy.foo().bar().wait(100);
```
> Catch chained wait

- lib/rules/require-data-selectors.js
- tests/lib/rules/require-data-selectors.js
Closes https://github.com/cypress-io/eslint-plugin-cypress/issues/37
Check for nodeType to be `TemplateLiteral` and quasis cooked value to start with `[data-`
> fix: require data selectors support template literal

- README.md
No need for `plugins` and rule-extending if using recommended friendly config
> Demo not needing `plugins` and rule-extending for friendly plugin

- lib/rules/no-assigning-return-values.js
Add support for ESLint v4
Resolves #14 
- `npm i eslint@4.x.x`
- `npm start`
- https://eslint.org/docs/user-guide/migrating-to-5.0.0#parent-before-rules
> fix: no-assigning-return-values eslint 4, Resolves #14

- lib/rules/require-data-selectors.js
- tests/lib/rules/require-data-selectors.js
- Fixes #44
Hi !
This should fix #44.
It considers valid selectors that start with the character `@` as well as those that start with `[data-`.
I've added tests for both string and template literals.
Please let me know if I've missed anything or if there is a formatting problem.
Thanks for maintaining this eslint plugin ! :)
> fix: Allow aliases in require-data-selectors rule

- lib/rules/no-assigning-return-values.js
- tests/lib/rules/no-assigning-return-values.js
fixes #56 
This corrects the lint errors that are thrown with the bundled examples of cypress v4.6.
I don't know the API well enough to know if chaining more commands and returning the results is valid and should be covered here. But this is a start :)
> fix: allow assignment of children of whitelisted commands in no-assigning-return-values rule

- index.js
> fix: Fix cypress/no-async-tests not found error

- lib/rules/no-unnecessary-waiting.js
Fixes #69 
As pointed out in the developer guide
https://eslint.org/docs/developer-guide/scope-manager-interface#deprecated-members-2
scope.resolve method is deprecated. For that reason it was not implemented
in `typescript-eslint/typescript-eslint` and `no-unnecessary-waiting` rule
fails with version 4.x of the typescript eslint parser.
The eslint developer guide suggest to use `scope.references.find` instead.
> fix: Replace deprecated scope.resolve method

- README.md
- tests/lib/rules/no-unnecessary-waiting.js
closes #80
added a few sanity tests to confirm
> chore(docs): Explain how to temporarily disable rules

- lib/rules/no-force.js
- tests/lib/rules/no-force.js
This was causing my Eslint to crash, I think on the cy.document({ log: false }) nodes if someone is interested in that, so just quickly fixed it
> fix: Fix crashing bug in no-force rule when using spread operator

- README.md
- docs/rules/no-pause.md
- lib/rules/no-pause.js
- tests/lib/rules/no-pause.js
Partial implementation for #74 which disallows the parent `cy.pause()` command. We have occasionally left `cy.pause` command in the specs which always surprises the other developers when they use `cypress open`.
> Add no cy.pause() command rule

- index.js
Just noticed this new rule and wanted to try it out, but it seemed to be not actually used
https://github.com/cypress-io/eslint-plugin-cypress/pull/85
> fix: Properly export "no-pause" rule

- index.js
This is kinda urgent because if you sync the latest package you get error saying the rule doesn't exist, for not being registered properly:
`Definition for rule 'cypress/unsafe-to-chain-command' was not found `
> fix: Solve unsafe to chain command does not exist

- lib/rules/unsafe-to-chain-command.js
Wait command [is documented as unsafe to chain](https://docs.cypress.io/api/commands/wait#When-given-a-time-argument), but that might be an oversight in the documentation since there are documented use cases for wait action.
> fix: Wait incorrectly reported as unsafe to chain

- lib/rules/no-unnecessary-waiting.js
- tests/lib/rules/no-unnecessary-waiting.js
This PR adds proper handling for ImportBindings in `no-unnecessary-waiting` rule to prevent reporting codes like this:
```js
// We don't know if WAIT is a number or alias '@someRequest'
import { WAIT } from './constnats'
cy.wait(WAIT)
```
It's similar to the existing case with function arguments where we cannot see the type of the argument. Similarly, we cannot know the type of import binding.
```js
// function wait (amount) { cy.wait(amount) }
// we can't know the type of value, so don't fail
if (!param || param.type !== 'AssignmentPattern') return false
```
Resolves https://github.com/cypress-io/eslint-plugin-cypress/issues/43
> Handle ImportBindings in `no-unnecessary-waiting` rule

- circle.yml
- package-lock.json
- Upgrades docker images from Node 8 to Node 16 so that we can support modern syntax in dependencies
- Updates package-lock file to version 2, for a seamless experience in Node 16
> ci(docker): upgrades ci images from node 8 to node 16

- package-lock.json
- package.json
This version bump ensures the `eslint-plugin-cypress` works with latest `eslint` flat config.
The versions of `globals` before `13.12.1` had a typo in `AudioWorkletGlobalScope` key which was fixed by https://github.com/sindresorhus/globals/pull/184
> fix: bump globals to latest

- lib/rules/unsafe-to-chain-command.js
- tests/lib/rules/unsafe-to-chain-command.js
I was recently using [Cypress Real Events](https://github.com/dmtrKovalenko/cypress-real-events) in one of my projects, and I realized that the `unsafe-to-chain-command` rule wasn't triggering errors when using the library's custom Cypress functions. I thought it would be nice to have the ability to pass in additional methods to lint for when using this rule.
- Added `methods` option to allow for linting on custom Cypress commands
- Takes in either a string or regex 
- Refactored `isRootCypress` to use recursion instead of a `while` loop + mutation
- Added types via JSDoc TypeScript syntax
- Added appropriate test cases
- Utilized JSON Schema via ESLint's custom rule API
Users can now pass in `methods` to the rule like so:
```js
"cypress/unsafe-to-chain-command": [
"error",
{
"methods": [ …
```
> feat: add option to `unsafe-to-chain-command` rule to allow custom Cypress command linting

- lib/rules/unsafe-to-chain-command.js
- tests/lib/rules/unsafe-to-chain-command.js
going to revert #142 and re apply commits as a single squash merged commit to trigger semantic release on the re apply PR
> chore: revert merge for semantic release

- lib/rules/unsafe-to-chain-command.js
- tests/lib/rules/unsafe-to-chain-command.js
re applies #142 as a `fix` commit when we squash-merge this commit in
> fix: unsafe-to-chain-command: Fix the false positive of 'focus' regex matching 'focused'

- .husky/pre-commit
- package-lock.json
- package.json
When committing to the repo, the Husky hook outputs a deprecation message:
> Warning: Setting pre-commit script in package.json > scripts will be deprecated
> Please move it to husky.hooks in package.json, a .huskyrc file, or a husky.config.js file
> Or run ./node_modules/.bin/husky-upgrade for automatic update
and an npm support warning message such as:
> husky > pre-commit (node v16.15.0)
> npm WARN npm npm does not support Node.js v16.15.0
> npm WARN npm You should probably upgrade to a newer version of node as we
> npm WARN npm can't make any promises that npm will work with this version.
> npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
> npm WARN npm You can find the latest version at https://nodejs.org/
- Husky is updated to …
> chore: update husky to 8.0.3

- package.json
The script `lint` fails to run on Microsoft Windows operating systems. The error is:
```text
$ npm run lint
> eslint-plugin-cypress@0.0.0-development lint
> eslint '*.js' '**/**/*.js'
Oops! Something went wrong! :(
ESLint: 5.16.0.
No files matching the pattern "'*.js'" were found.
Please check for typing mistakes in the pattern.
```
The single-quotes in the script definition `lint` are changed to double-quotes and escaped for cross-compatibility with Windows.
On Ubuntu `22.04.4` LTS and on Windows 11 with Node.js `16.15.0` execute
```shell
npm ci
npm run lint
```
The output from the lint script should be as follows with no errors reported:
```shell
$ npm run lint
> eslint-plugin-cypress@0.0.0-development lint
> eslint "*.js" "**/**/*.js"
```
> chore: make lint script Windows compatible

- README.md
- docs/rules/no-async-before.md
- lib/rules/no-async-before.js
- tests/lib/rules/no-async-before.js
PR for adding linting rules to the before and beforeEach. Having an async in the beforeEach and before can introduce unexpected behaviour, where the async process is not finished yet before the test runs. This can cause a test to be flaky. This rule will mark it as an error.
> Feat: add linting rule for before/beforeEach just like the async test rule

- circle.yml
- relates to issue #163 
- Using the following test scripts in CircleCI results in failure if the npm module semantic-release is updated (see failure in PR https://github.com/cypress-io/eslint-plugin-cypress/pull/162):
- `"test:v4": "npm i eslint@4.x && npm run test"`
- `"test:v6": "npm i eslint@6.x && npm run test"`
This combination is causing an incompatible version of npm to be used. This problematic npm version is provided through the npm module `semantic-release`.
1. Convert calls from `npm install` to `npm ci`.
`npm ci` was released with [npm@5.7.0](https://github.com/npm/npm/releases/tag/v5.7.0) in Feb 2018
2. Make installation and test of alternate versions into two separate steps.
> ci: remove dependency on semantic-release npm

- package-lock.json
- package.json
The currently configured dependency [semantic-release@15.13.18](https://github.com/semantic-release/semantic-release/releases/tag/v15.13.18) is out of date. Installing this version produces a deprecation warning and a high number of vulnerabilities.
Update to [semantic-release@19.0.3](https://github.com/semantic-release/semantic-release/releases/tag/v19.0.3). This is the same version used by [cypress-io/cypress](https://github.com/cypress-io/cypress). (`semantic-release@20.x` already requires Node.js `18` so this is currently not compatible with this repo and cannot be used yet.)
> fix(deps): update semantic-release to 19.0.3

- circle.yml
- package.json
related to issues:
- #166
- #153
- #157
- closes #163
[@cypress/eslint-plugin-dev@3.2.0](https://github.com/cypress-io/eslint-plugin-dev/tree/v3.2.0) configured in this repo's `devDependencies` contains `peerDependencies`:
```json
"@typescript-eslint/parser": ">= 1.11.0"
"eslint": ">= 3.2.1 < 6"
```
however
[@typescript-eslint/parser@1.11.0](https://github.com/typescript-eslint/typescript-eslint/blob/v1.11.0/packages/parser) is only compatible with ESLint `5`:
```json
"eslint": "^5.0.0"
```
This rules out the supported use of ESLint `4` for dev linting tests in the repository.
Remove tests for ESLint `4`.
The last release of ESLint 4.x was [eslint@4.19.1](https://github.com/eslint/eslint/releases/tag/v4.19.1) released on March 22, 2018, more than 6 years ago. The current release is …
> test: drop testing of ESLint 4

- package-lock.json
- package.json
The repo is currently configured with `jest@^24.8.0` and is using [jest@24.8.0](https://github.com/jestjs/jest/releases/tag/v24.8.0).
This version of `jest` reports many deprecations and 16 vulnerabilities.
- Update the dependency `jest` to [jest@^29.7.0](https://github.com/jestjs/jest/releases/tag/v29.7.0).
- Remove the conflicting configuration key `jest` with `testMatch` pattern from [package.json](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/package.json). A different `testMatch` pattern is defined in [jest.config.js](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/jest.config.js) which causes a run-time error "Multiple configurations found" in `jest@27` and later.
On Ubuntu `22.04.4` LTS with Node.js `20.12.2` execute
```shell
npm test
```
and …
> chore(deps): update jest to 29.7.0

- circle.yml
- package-lock.json
- package.json
- contributes to resolution of issue https://github.com/cypress-io/eslint-plugin-cypress/issues/157
The repo is currently based on [eslint@5.16.0](https://github.com/eslint/eslint/releases/tag/v5.16.0) released on Mar 30, 2019. This is an old version released 5 years ago and the repo needs to be moved towards compatibility with the current version ESLint `9.x`.
1. The repo base version is updated to [eslint@7.32.0](https://github.com/eslint/eslint/releases/tag/v7.32.0) released on Jul 31, 2021. This version of ESLint is used for the Lint test in CircleCI. ESLint `7.x` is an intermediate step in the journey towards supporting ESLint `9.x`.
2. The following two modules are updated:
- `@cypress/eslint-plugin-dev@3.2.0` (latest `3.x` release.)
- `@cypress/eslint-plugin-json@3.2.1` (latest …
> chore(deps): update eslint to 7.32.0

- README.md
- circle.yml
- package-lock.json
- package.json
BREAKING CHANGE: Support ESLint v7 and v8 only
- closes https://github.com/cypress-io/eslint-plugin-cypress/issues/89
- closes https://github.com/cypress-io/eslint-plugin-cypress/issues/175
The `eslint-plugin-cypress` plugin currently defines `peerDependencies` of `"eslint": ">= 3.2.1"`. This includes versions of ESLint `v3`, `v4` and `v9` which are not compatible with the current latest version of `eslint-plugin-cypress@2.15.2` (including its other `peerDependencies`). ESLint `v8` cannot be linted by `@cypress/eslint-plugin-dev` and replacement linting recommended by [Linting a Plugin](https://eslint.org/docs/latest/extend/plugins#linting-a-plugin) only covers ESLint `v7` and above.
The intersection of supportable combinations is ESLint `v7` and `v8` only.
Support ESlint `v7` & `v8` …
> feat: support eslint v7 & v8 instead of ">= 3.2.1"

- README.md
- closes #180
Users have requested linting support to detect `.only` and `.skip` constructs in Cypress test specs and have submitted issues and PRs to have these rules built in to `eslint-plugin-cypress`. Adding these rules into the Cypress plugin would however duplicate the following existing working and comprehensive rules in [eslint-plugin-mocha](https://www.npmjs.com/package/eslint-plugin-mocha):
- [mocha/no-exclusive-tests](https://github.com/lo1tuma/eslint-plugin-mocha/blob/HEAD/docs/rules/no-exclusive-tests.md) to warn about the use of  `describe.only`, `it.only`, `suite.only`, `test.only`, `context.only` and `specify.only` within the source code.
- [mocha/no-skipped-tests](https://github.com/lo1tuma/eslint-plugin-mocha/blob/a936f2ace2191d0b26b70a34e19711e6a4252659/docs/rules/no-ski …
> docs: add mocha instructions to readme

- circle.yml
When alternative versions of ESLint are installed by the [circle.yml](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/circle.yml) workflow, the version of ESLint is not logged. This makes troubleshooting more difficult.
In the current transition phase, whilst dependencies are being updated in incremental steps, it is unavoidable that peer dependency errors are logged. npm does not make it clear which version of ESLint it has chosen for installation.
- See also https://github.com/cypress-io/eslint-plugin-cypress/pull/182#issuecomment-2069416309
The exact version of ESLint is shown with the [CLI option `--version`](https://eslint.org/docs/latest/use/command-line-interface#-v---version), for example `v8.57.0`:
```shell
npx eslint --version
```
> ci: display exact eslint version in circleci

- CONTRIBUTING.md
- package.json
1. The script `start` is defined in package.json as `yarn run test-watch` using the Yarn package manager.
https://github.com/cypress-io/eslint-plugin-cypress/blob/455dc131960e6a55a24c18960e49e893c8862e6f/package.json#L45
2. [CONTRIBUTING.md](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/CONTRIBUTING.md) invites to use
> * Run `yarn start` or `npm start`
The use of Yarn seems out of place, as the rest of the repository, such as [circle.yml](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/circle.yml) is using npm not Yarn. The repo is locked with [package-lock.json](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/package-lock.json). There is no `yarn.lock` in the repository.
3. Only the `start` script is mentioned. The `test` script is not …
> chore: harmonize and describe jest usage

- .eslintrc.json
- package-lock.json
- package.json
- tests/lib/rules/require-data-selectors.js
- closes #174
- The previous set of plugins used internally (`npm run lint`) were based on the npm module [@cypress/eslint-plugin-dev](https://www.npmjs.com/package/@cypress/eslint-plugin-dev). Since this module is not yet compatible with ESLint `8.x`, a migration to this version has not been possible. PR https://github.com/cypress-io/cypress/pull/29355 aims to migrate [@cypress/eslint-plugin-dev](https://www.npmjs.com/package/@cypress/eslint-plugin-dev) to ESLint `8.x`, however a path to ESLint `9.x` needs to be possible and the current PR for [@cypress/eslint-plugin-dev](https://www.npmjs.com/package/@cypress/eslint-plugin-dev) does not cover this aspect.
1. Plugin dependencies used for internal linting are removed:
- `@cypress/eslint-plugin-dev`
- `@cypress/eslint-plugin-json`
- …
> refactor: migrate internal linting to recommended plugins

- circle.yml
- package-lock.json
- package.json
The repo is currently linting itself in CircleCI using ESLint `7.x`. This causes a peer dependency warning from
```text
npm WARN Could not resolve dependency:
npm WARN peer eslint@">=8" from eslint-plugin-es-x@7.6.0
npm WARN node_modules/eslint-plugin-n/node_modules/eslint-plugin-es-x
npm WARN   eslint-plugin-es-x@"^7.5.0" from eslint-plugin-n@16.6.2
npm WARN   node_modules/eslint-plugin-n
```
Move internal linting to using ESLint `8.x` and prevent peer dependency warnings.
- update [eslint](https://www.npmjs.com/package/eslint) to `v8.x` ([eslint@8.57.0](https://github.com/eslint/eslint/releases/tag/v8.57.0) - latest `v8.x` release)
- update [eslint-plugin-eslint-plugin](https://www.npmjs.com/package/eslint-plugin-eslint-plugin) to `v6.x` …
> chore(deps): update internal linting to eslint 8.57.0

- .eslintrc.json
- lib/rules/assertion-before-screenshot.js
- lib/rules/no-assigning-return-values.js
- lib/rules/no-async-before.js
- lib/rules/no-async-tests.js
- lib/rules/no-force.js
- lib/rules/no-pause.js
- lib/rules/no-unnecessary-waiting.js
- lib/rules/require-data-selectors.js
- lib/rules/unsafe-to-chain-command.js
- supports resolution of issue https://github.com/cypress-io/eslint-plugin-cypress/issues/184
The `plugin:eslint-plugin/recommended` rules of [eslint-plugin-eslint-plugin](https://www.npmjs.com/package/eslint-plugin-eslint-plugin) include the [eslint-plugin/require-meta-type](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/main/docs/rules/require-meta-type.md) rule. This rule currently fails for all of the Cypress rules if enabled, since none of these has a `meta.type` defined.
According to the ESLint documentation [Rule Structure](https://eslint.org/docs/latest/extend/custom-rules#rule-structure):
> `meta`: (`object`) Contains metadata for the rule:
>
> * `type`: (`string`) Indicates the type of rule, which is one of `"problem"`, `"suggestion"`, or `"layout"`:
>
> …
> chore: add meta.type to rules

- .eslintrc.json
- lib/rules/assertion-before-screenshot.js
- lib/rules/no-assigning-return-values.js
- lib/rules/no-async-before.js
- lib/rules/no-async-tests.js
- lib/rules/no-force.js
- lib/rules/no-pause.js
- lib/rules/no-unnecessary-waiting.js
- lib/rules/require-data-selectors.js
- lib/rules/unsafe-to-chain-command.js
- supports resolution of issue https://github.com/cypress-io/eslint-plugin-cypress/issues/184
The [eslint-plugin/require-meta-docs-url](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/main/docs/rules/require-meta-docs-url.md) rule of [eslint-plugin-eslint-plugin](https://www.npmjs.com/package/eslint-plugin-eslint-plugin) requires that the `meta.docs.url` property is populated.
Rules with no  `meta.docs.url` property defined:
| Rule document                                                                                                                            |
| :--------------------------------------------------------------------------------------------------------------------------------------- |
| [assertion-before-screenshot](https://github.com/cypress-io/eslint …
> chore: standardize meta.url property

- index.js
- partially addresses issue https://github.com/cypress-io/eslint-plugin-cypress/issues/190
- The rule [no-async-before](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/docs/rules/no-async-before.md) provided by PR https://github.com/cypress-io/eslint-plugin-cypress/pull/151 is not found when attempting to use it:
```text
1:1  error  Definition for rule 'cypress/no-async-before' was not found  cypress/no-async-before
```
Added [no-async-before](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/docs/rules/no-async-before.md) to [index.js](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/index.js).
> fix: enable cypress/no-async-before

- .eslintrc.json
- lib/rules/assertion-before-screenshot.js
- lib/rules/no-assigning-return-values.js
- lib/rules/no-async-before.js
- lib/rules/no-async-tests.js
- lib/rules/no-force.js
- lib/rules/no-pause.js
- lib/rules/no-unnecessary-waiting.js
- lib/rules/require-data-selectors.js
- lib/rules/unsafe-to-chain-command.js
The [eslint-plugin/require-meta-docs-description](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/HEAD/docs/rules/require-meta-docs-description.md) rule of [eslint-plugin-eslint-plugin](https://www.npmjs.com/package/eslint-plugin-eslint-plugin) requires that the `meta.docs.description` property is properly populated. In particular it requires each rule to start with one of:
- enforce
- require
- disallow
None of the rule descriptions exactly meet this requirement.
| Rule                          | Current README description                                      | Current meta.docs.description                                                                       |
| :---------------------------- | :-------------------------------------------------------------- | …
> chore: standardize meta.docs.description property

- docs/rules/no-async-before.md
- docs/rules/no-async-tests.md
The following rules documents contain outdated links concerning Promises:
- [no-async-before > Further Reading](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/docs/rules/no-async-before.md#further-reading)
- [no-async-tests > Further Reading](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/docs/rules/no-async-tests.md#further-reading)
The outdated links are:
- [Commands Are Promises](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Commands-Are-Promises)
The target `https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Commands-Are-Promises` does not exist.
- [Commands Are Not Promises](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Commands-Are-Not-Promises)
The target …
> docs: fix async further reading links

- .eslintrc.json
The instructions in the original ESLint blog post [Preparing your custom rules for ESLint v9.0.0](https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/) for converting the deprecated `context.getScope()` and `context.getAncestors()` did not work for ESLint `>=7 <=8.3.0`.
- I reported this in issue https://github.com/eslint/eslint.org/issues/559.
- The ESLint team responded with PR https://github.com/eslint/eslint.org/pull/560.
The new suggestions involve using the [Nullish coalescing operator (??)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing). The code falls back to previous API standards if the new API calls aren't available, so it can be used flexibly in old and new ESLint versions.
The new suggestions however fail linting …
> chore(deps): bump to ecmaVersion 2020

- lib/rules/no-async-before.js
- lib/rules/no-async-tests.js
- lib/rules/no-unnecessary-waiting.js
- closes https://github.com/cypress-io/eslint-plugin-cypress/issues/154
-  [no-unnecessary-waiting](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/lib/rules/no-unnecessary-waiting.js) rule is using `context.getScope()`
-  [no-async-tests](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/lib/rules/no-async-tests.js) rule is using `context.getAncestors()`
-  [no-async-before](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/lib/rules/no-async-before.js) rule is using `context.getAncestors()`
These methods are deprecated in ESLint `8.x` ([eslint@8.50.0](https://github.com/eslint/eslint/releases/tag/v8.5.0) and later `8.x` releases), causing warnings, and removed in ESLint `9.x` ([eslint@9.0.0](https://github.com/eslint/eslint/releases/tag/v9.0.0) …
> fix: convert deprecated context calls

- .husky/pre-commit
- package-lock.json
- package.json
- The repo is using [husky@8.0.3](https://github.com/typicode/husky/releases/tag/v8.0.3) which is not the recommended currently supported [Husky](https://typicode.github.io/husky/) `9.x` version. The current release is [husky@9.0.11](https://github.com/typicode/husky/releases/tag/v9.0.11).
- The release [Husky 9.x](https://github.com/typicode/husky/releases/tag/v9.0.1) dropped support for Node.js `14` and `16`, so PR #159 was restricted at the time to using Husky `8.x` because CircleCI was running on Node.js `16`.
- PR #171 updated the CircleCI workflow in this repo to use Node.js `v20.12.2` removing the restriction for Husky `9.x`.
- Husky is updated to [husky@9.0.11](https://github.com/typicode/husky/releases/tag/v9.0.11) released on Feb 14, 2024.
- The previous update in PR #159 …
> chore(deps): update husky to 9.0.11

- README.md
- supports resolution of issue #193
This PR deals with the [README > Rules](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/README.md#rules) section.
1. The rule descriptions do not agree with the [lib/rules](https://github.com/cypress-io/eslint-plugin-cypress/tree/master/lib/rules) property `meta.docs.description`.
2. The rules are only sorted according to inclusion in the recommended set. Otherwise there is no recognizable sorting order.
3. The entry for [no-async-before](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/docs/rules/no-async-before.md) is missing (part of issue #193)
1. The rule table is formatted and populated according to the standard derived from the [eslint-doc-generator](https://www.npmjs.com/package/eslint-doc-generator)
2. The rule …
> docs: rule readme harmonization

- .eslintrc.js
[ESLint 8.x configuration files](https://eslint.org/docs/v8.x/use/configure/configuration-files) in JSON format become [deprecated in ESLint 9.x](https://eslint.org/docs/latest/use/configure/configuration-files-deprecated) which only uses JavaScript format.
The [.eslintrc.json](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/.eslintrc.json) ESLint configuration file is converted to `.eslintrc.js` (JavaScript). (Note that this does not convert to a "flat config" format, which is left for a later migration stage.)
This is one building block contributing to a migration from ESLint `8.x` to ESLint `9.x`.
On Ubuntu `22.04.4` LTS, Node.js `20.12.2` LTS
```shell
npm ci
npm run lint
```
- [ESLint 8.x configuration files](https://eslint.org/docs/v8.x/use/configure/configuration-file …
> refactor: convert config .eslintrc.json to .js

- docs/rules/assertion-before-screenshot.md
- docs/rules/no-assigning-return-values.md
- docs/rules/no-async-before.md
- docs/rules/no-async-tests.md
- docs/rules/no-force.md
- docs/rules/no-pause.md
- docs/rules/no-unnecessary-waiting.md
- docs/rules/require-data-selectors.md
- docs/rules/unsafe-to-chain-command.md
- supports resolution of issue #193
This PR deals with issues in the set of 9 [docs/rules](https://github.com/cypress-io/eslint-plugin-cypress/tree/master/docs/rules) Markdown files.
1. The top-level headers of the `docs/rules` documents do not agree with the [lib/rules](https://github.com/cypress-io/eslint-plugin-cypress/tree/master/lib/rules) property `meta.docs.description`.
2. Some headers do not include the name of the rule.
3. Formatting of the `docs/rules` documents is inconsistent.
1. Top-level headers of the `docs/rules` documents are built using the `meta.docs.description` property from the corresponding [lib/rules](https://github.com/cypress-io/eslint-plugin-cypress/tree/master/lib/rules) source.
2. The `docs/rules` top-level header has the name of the rule in the form …
> docs: rule documentation harmonization

- package-lock.json
- package.json
- The currently configured dependency [semantic-release@19.0.3](https://github.com/semantic-release/semantic-release/releases/tag/v19.0.3), released in June 2022, and updated through #162, reports 6 moderate severity vulnerabilities.
- The release [semantic-release@20.0.0](https://github.com/semantic-release/semantic-release/releases/tag/v20.0.0) dropped support for Node.js < `18` , so PR #162 was restricted at the time to using semantic-release `19.x` because CircleCI was running on Node.js `16`.
- PR #171 updated the CircleCI workflow in this repo to use Node.js `v20.12.2` removing the restriction on later `semantic-release` versions.
Update to [semantic-release@23.0.8](https://github.com/semantic-release/semantic-release/releases/tag/v23.0.8), released on Apr 9, 2024, to remediate …
> fix(deps): update semantic-release to 23.0.8

- docs/rules/no-pause.md
- lib/rules/no-pause.js
- tests/lib/rules/no-pause.js
The `cypress/no-pause` rule only applies to a parent node. 
Convert the `isCypressCall` function into a recursive function to detect chained calls such as `cy.get("...").pause();`.
Closes #147
> feat: apply no-pause rule recursively

- FLAT-CONFIG.md
- README.md
- relates to issue #146
The [README > Usage](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/README.md#usage) section describes how to add an `.eslintrc.json` configuration file to use the `eslint-plugin-cypress` plugin. With the announcement and release of [ESLint v9](https://eslint.org/blog/2024/04/eslint-v9.0.0-released/) on Apr 5, 2024, configuration files in the format `.eslintrc.*` have become deprecated (see [ESLint 8.x Configuration Files](https://eslint.org/docs/v8.x/use/configure/configuration-files)).
The plugin needs to document how to set up and use non-deprecated [Configuration Files (New)](https://eslint.org/docs/v8.x/use/configure/configuration-files-new) for ESLint `v8`. These are JavaScript files using an `eslint.config.*js` naming convention. Users of …
> docs: add document for FlatCompat use

- circle.yml
- jest.config-legacy.js
- package.json
- tests-legacy/config.js
- tests-legacy/lib/rules/assertion-before-screenshot.js
- tests-legacy/lib/rules/no-assigning-return-values.js
- tests-legacy/lib/rules/no-async-before.js
- tests-legacy/lib/rules/no-async-tests.js
- tests-legacy/lib/rules/no-force.js
- tests-legacy/lib/rules/no-pause.js
- tests-legacy/lib/rules/no-unnecessary-waiting.js
- tests-legacy/lib/rules/require-data-selectors.js
- tests-legacy/lib/rules/unsafe-to-chain-command.js
Tests in the [tests/lib/rules](https://github.com/cypress-io/eslint-plugin-cypress/tree/master/tests/lib/rules) which run internally under ESLint `7.x` and `8.x` are not compatible with ESLint `9.x`.
The guide [Migrate to 9.0 > FlatRuleTester is now RuleTester](https://eslint.org/docs/latest/use/migrate-to-9.0.0#flat-rule-tester) explains:
> As announced in our [blog post](https://eslint.org/blog/2023/10/flat-config-rollout-plans/), the temporary FlatRuleTester class has been renamed to RuleTester, while the RuleTester class from v8.x has been removed. Additionally, the FlatRuleTester export from eslint/use-at-your-own-risk has been removed.
This is a breaking change for the tests.
The enhancement goal is to be able to test the repo rules using each of the supported versions of ESLint: …
> tests: save legacy tests

- CONTRIBUTING.md
The [CONTRIBUTING](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/CONTRIBUTING.md) document is reworked and expanded in detail.
- The following step was added to the instructions. The fact that this was missing has led to rules being published inactive in the past. (See history of [index.js](https://github.com/cypress-io/eslint-plugin-cypress/commits/master/index.js) listing multiple examples of this mistake over the years.)
> Add the rule to [index.js](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/index.js)
The following sections are added:
- Preparation
- Rule references
- New rule
- Document generation
- Legacy tests
Generally the level of detail has been increased.
The utility ESLint [eslint-doc-generator](https://www.npmjs.com/package/eslint-doc-gene …
> docs: rework contributor instructions

- circle.yml
- tests/lib/rules/assertion-before-screenshot.js
- tests/lib/rules/no-assigning-return-values.js
- tests/lib/rules/no-async-before.js
- tests/lib/rules/no-async-tests.js
- tests/lib/rules/no-force.js
- tests/lib/rules/no-pause.js
- tests/lib/rules/no-unnecessary-waiting.js
- tests/lib/rules/require-data-selectors.js
- tests/lib/rules/unsafe-to-chain-command.js
- Part 2: Following on from PR https://github.com/cypress-io/eslint-plugin-cypress/pull/205
Tests in the [tests/lib/rules](https://github.com/cypress-io/eslint-plugin-cypress/tree/master/tests/lib/rules) which run internally under ESLint `7.x` and `8.x` are not compatible with ESLint `9.x`.
The guide [Migrate to 9.0 > FlatRuleTester is now RuleTester](https://eslint.org/docs/latest/use/migrate-to-9.0.0#flat-rule-tester) explains:
> As announced in our [blog post](https://eslint.org/blog/2023/10/flat-config-rollout-plans/), the temporary FlatRuleTester class has been renamed to RuleTester, while the RuleTester class from v8.x has been removed. Additionally, the FlatRuleTester export from eslint/use-at-your-own-risk has been removed.
This is a breaking change for the tests.
The enhancement …
> chore: migrate to RuleTester v9

- package-lock.json
- package.json
The installed base version of ESLint is [eslint@8.57.0](https://github.com/eslint/eslint/releases/tag/v8.57.0)
CI [circle.yml](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/circle.yml) does however temporarily install each supported version ESLint `v7`, `v8` and `v9` during testing with Jest.
The repo is compatible with ESLint `v9` and can be updated.
Update the installed base version of ESLint to [eslint@9.2.0](https://github.com/eslint/eslint/releases/tag/v9.2.0) (latest).
```shell
npm ci
npm run lint
npm test
```
> chore(deps): update eslint to 9.2.0

- eslint.config.mjs
- tests-legacy/lib/rules/unsafe-to-chain-command.js
- tests/lib/rules/unsafe-to-chain-command.js
The [eslint-plugin-eslint-plugin](https://www.npmjs.com/package/eslint-plugin-eslint-plugin), for linting plugins, provides two rules to ensure consistent property ordering:
- [Enforce the order of meta properties (eslint-plugin/meta-property-ordering)](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/HEAD/docs/rules/meta-property-ordering.md)
- [Require the properties of a test case to be placed in a consistent order (eslint-plugin/test-case-property-ordering)](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/HEAD/docs/rules/test-case-property-ordering.md)
These rules are not part of the `flat/recommended` set of [eslint-plugin-eslint-plugin](https://www.npmjs.com/package/eslint-plugin-eslint-plugin) and are currently not applied. They are however …
> test: add property ordering rules

- package-lock.json
- package.json
This is a routine maintenance update, prior to releasing the ESLint flat config PR (https://github.com/cypress-io/eslint-plugin-cypress/pull/212) for review.
Update to
- [eslint@9.3.0](https://github.com/eslint/eslint/releases/tag/v9.3.0)
- [@eslint/js@9.3.0](https://github.com/eslint/eslint/releases/tag/v9.3.0)
- [@eslint/eslintrc](https://github.com/eslint/eslintrc/releases/tag/v3.1.0)
- [eslint-plugin-n@17.7.0](https://github.com/eslint-community/eslint-plugin-n/releases/tag/v17.7.0)
> chore(deps): update eslint to 9.3.0 with plugin updates

- README.md
https://eslint.org/version-support/ notes that ESLint `v7` reached end-of-life on Apr 9, 2022. The last release of ESLint `v7.x` was [v7.32.0](https://github.com/eslint/eslint/releases/tag/v7.32.0) on Jul 31, 2021.
Add a deprecation section to the [README](https://github.com/MikeMcC399/eslint-plugin-cypress/blob/prime/README.md) document for ESLint `v7`.
There are no technical changes to the plugin caused by the deprecation.
https://eslint.org/version-support/
> docs: deprecate ESLint v7

- README.md
- docs/rules/no-debug.md
- legacy.js
- lib/flat.js
- lib/rules/no-debug.js
- tests/lib/rules/no-debug.js
Addresses https://github.com/cypress-io/eslint-plugin-cypress/issues/74
It's basically a duplicate of `no-pause`.
> feat: add rule no-debug

- package-lock.json
`npm audit` reports a high severity vulnerability:
```text
braces  <3.0.3
Severity: high
Uncontrolled resource consumption in braces - https://github.com/advisories/GHSA-grv7-fg5c-xmjg
fix available via `npm audit fix`
node_modules/braces
1 high severity vulnerability
```
Update to [braces@3.0.3](https://www.npmjs.com/package/braces/v/3.0.3) through `npm audit fix`.
```text
$ npm audit
found 0 vulnerabilities
```
`braces` is required by `semantic-release` only and is not involved in the execution of this plugin. Therefore it will not be tested until the next release of the plugin.
```text
└─┬ semantic-release@23.0.8
└─┬ micromatch@4.0.5
└── braces@3.0.3
```
> chore(deps): update braces to 3.0.3

- package-lock.json
- package.json
This is a routine maintenance update.
| Module                        | Before   | After                                                                                        |
| ----------------------------- | -------- | -------------------------------------------------------------------------------------------- |
| `eslint`                      | `9.3.0`  | [9.12.0](https://github.com/eslint/eslint/releases/tag/v9.12.0)                              |
| `@eslint/js`                  | `9.3.0`  | [9.12.0](https://github.com/eslint/eslint/releases/tag/v9.12.0)                              |
| `eslint-plugin-eslint-plugin` | `6.1.0`  | [6.2.0](https://github.com/eslint-community/eslint-plugin-eslint-plugin/releases/tag/v6.2.0) |
| `eslint-plugin-mocha`         | `10.4.3` | …
> chore(deps): update eslint to 9.12.0 and other eslint* deps

- package-lock.json
- package.json
- closes https://github.com/cypress-io/eslint-plugin-cypress/issues/229
The currently configured [semantic-release@23.0.8](https://github.com/semantic-release/semantic-release/releases/tag/v23.0.8)
displays a deprecation warning when installed:
> npm warn deprecated read-pkg-up@11.0.0: Renamed to read-package-up
Update to [semantic-release@24.1.2](https://github.com/semantic-release/semantic-release/releases/tag/v24.1.2)
Run `npm audit fix` due to `micromatch@4.0.5` vulnerability to update to `micromatch@4.0.8`.
> chore(deps): update semantic release to 24.1.2

- FLAT-CONFIG.md
- README.md
- circle.yml
- lib/flat.js
- package-lock.json
- package.json
- closes https://github.com/cypress-io/eslint-plugin-cypress/issues/228
- addresses issue https://github.com/cypress-io/eslint-plugin-cypress/issues/215 for flat config only
ESLint versions < `v9` are no longer supported (see https://eslint.org/version-support/). [eslint-plugin-cypress](https://github.com/cypress-io/eslint-plugin-cypress) cannot rely on unsupported ESLint versions.
Support for ESLint `v7` and `v8` is removed.
- Update `peerDependencies` in [package.json](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/package.json) to
`"eslint": ">=9"`
- Delete `test-v7` from [circle.yml](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/circle.yml)
- Update [globals](https://www.npmjs.com/package/globals) to …
> feat: minimum version eslint v9

- FLAT-CONFIG.md
The text and example code in [FLAT-CONFIG > Cypress and Mocha recommended](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/FLAT-CONFIG.md#cypress-and-mocha-recommended) disagree.
Whereas in the text it says:
> The settings for individual `mocha` rules from the `configs.flat.recommended` option are changed.
> - [mocha/no-exclusive-tests](https://github.com/lo1tuma/eslint-plugin-mocha/blob/main/docs/rules/no-exclusive-tests.md) and [mocha/no-skipped-tests](https://github.com/lo1tuma/eslint-plugin-mocha/blob/main/docs/rules/no-skipped-tests.md) are set to `error` instead of `warn`
the example sets the rule to `warn` which is the same as the setting from [eslint-plugin-mocha](https://www.npmjs.com/package/eslint-plugin-mocha)'s flat file recommended option …
> docs: correct mocha flat example

- FLAT-CONFIG.md
The flat example in [Cypress and Chai recommended](https://github.com/MikeMcC399/eslint-plugin-cypress/blob/prime/FLAT-CONFIG.md#cypress-and-chai-recommended) is outdated.
- [eslint-plugin-chai-friendly@0.8.0](https://github.com/ihordiachenko/eslint-plugin-chai-friendly/releases/tag/v0.8.0) shows the following message, indicating that the plugin version needs to be updated
> DEPRECATED ⚠️  - Critical bug fixed in 1.0.0
- [eslint-plugin-chai-friendly@1.0.0](https://github.com/ihordiachenko/eslint-plugin-chai-friendly/releases/tag/v1.0.0) renamed the flat configuration `recommended` to `recommendedFlat`
For the flat example in [Cypress and Chai recommended](https://github.com/MikeMcC399/eslint-plugin-cypress/blob/prime/FLAT-CONFIG.md#cypress-and-chai-recommended):
- remove the information …
> docs: update chai-friendly flat example

- package-lock.json
- package.json
This is a routine maintenance update.
| Module                        | Before   | After                                                                                        |
| ----------------------------- | -------- | -------------------------------------------------------------------------------------------- |
| `eslint`                      | `9.12.0` | [9.13.0](https://github.com/eslint/eslint/releases/tag/v9.13.0)                              |
| `eslint-plugin-eslint-plugin` | `6.2.0`  | [6.3.1](https://github.com/eslint-community/eslint-plugin-eslint-plugin/releases/tag/v6.3.1) |
Node.js `v20.18.0` LTS
```shell
npm ci
npm test
npm run lint
```
> chore(deps): update eslint to 9.13.0 and other eslint* deps

- circle.yml
The [circle.yml](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/circle.yml) workflow currently runs jobs using the [CircleCI Docker `cimg/node` image](https://circleci.com/developer/images/image/cimg/node) `cimg/node:20.12.2`. According to the [Node.js release schedule](https://github.com/nodejs/release#release-schedule) `20.x` moved to Maintenance LTS status on Oct 22, 2024.
The follow-on Node.js Active LTS version is Node.js `22.x`, which starts with the release of [Node.js 22.11.0](https://nodejs.org/en/blog/release/v22.11.0).
Update the [circle.yml](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/circle.yml) workflow to run jobs using the [CircleCI Docker `cimg/node` image](https://circleci.com/developer/images/image/cimg/node) `cimg/node:22.11.0` …
> ci(deps): update to cimg/node:22.11.0

- eslint.config.mjs
- package-lock.json
- package.json
[eslint-plugin-n](https://www.npmjs.com/package/eslint-plugin-n) produces a false positive when executing:
```shell
npx eslint
```
with the error:
```text
cypress-io/eslint-plugin-cypress/eslint.config.mjs
1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'
```
This is false - see [Node.js ESM enabling](https://nodejs.org/docs/latest/api/esm.html#enabling):
> Authors can tell Node.js to interpret JavaScript as an ES module via the `.mjs` file extension ...
- https://github.com/eslint-community/eslint-plugin-n/issues/327 has been open since Aug 2024 regarding this issue.
Remove [eslint-plugin-n](https://www.npmjs.com/package/eslint-plugin-n) from the linting configuration. It can be re-added if the above issue is resolved.
> chore(deps): remove eslint-plugin-n

- package-lock.json
- package.json
`npm audit` reports
> 7 vulnerabilities (1 low, 5 moderate, 1 high)
Since `globals` is a `dependency` the update also affects the published package.
Update all dependencies according to:
```shell
npm update --save
```
| Dependency                                                                               | Before  | After                                                                                        |
| ---------------------------------------------------------------------------------------- | ------- | -------------------------------------------------------------------------------------------- |
| [globals](https://www.npmjs.com/package/globals)                                         | 15.11.0 | [15.15.0](https://github.com/sindresorhus/globals/releases/tag/v15.15.0) …
> fix(deps): update all dependencies

- CONTRIBUTING.md
- relates to https://github.com/cypress-io/eslint-plugin-cypress/issues/250
The [CONTRIBUTING](https://github.com/cypress-io/github-action/blob/master/CONTRIBUTING.md) document contains no guidance for maintainers who merge pull requests.
Add a section to the [CONTRIBUTING](https://github.com/cypress-io/github-action/blob/master/CONTRIBUTING.md) document, similar to the [Cypress GitHub Action > Merging pull requests](https://github.com/cypress-io/github-action/blob/master/CONTRIBUTING.md#merging-pull-requests) document section.
> docs: add PR merge guidelines for maintainers

- README.md
- docs/rules/no-chained-get.md
- legacy.js
- lib/flat.js
- lib/rules/no-chained-get.js
- tests/lib/rules/no-chained-get.js
This PR creates a new rule to disallow the usage of `cy.get().get()` as `.get()` is often misused as it is starting search from the document and the previously selected element.
- Closes #134
> feat: add no-chained-get rule

- eslint.config.mjs
- package-lock.json
- package.json
This repo uses
https://github.com/cypress-io/eslint-plugin-cypress/blob/2c911ac76dad352fba1cd5e24fb6decb63118072/package.json#L34
The recent release [eslint-plugin-mocha@11.0.0](https://github.com/lo1tuma/eslint-plugin-mocha/releases/tag/11.0.0) has breaking changes including:
- Remove support for legacy configs and make the flat configs the default
- Migrate from [eslint-plugin-mocha@10.5.0](https://github.com/lo1tuma/eslint-plugin-mocha/releases/tag/10.5.0) to [eslint-plugin-mocha@11.1.0](https://github.com/lo1tuma/eslint-plugin-mocha/releases/tag/11.1.0) (current `latest`) for internal testing
- In [eslint.config.mjs](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/eslint.config.mjs) change from `mochaPlugin.configs.flat.recommended` to `mochaPlugin.configs.recommended`
> chore(deps): update eslint-plugin-mocha to 11.1.0

- package-lock.json
- package.json
- The repo is currently configured to use [eslint@9.24.0](https://github.com/eslint/eslint/releases/tag/v9.24.0), released Apr 4, 2025
- The latest version is [eslint@9.27.0](https://github.com/eslint/eslint/releases/tag/v9.27.0), released May 16, 2025.
Update from [eslint@9.24.0](https://github.com/eslint/eslint/releases/tag/v9.24.0) to [eslint@9.27.0](https://github.com/eslint/eslint/releases/tag/v9.27.0)
This is a housekeeping update, so that follow-on PRs will be based on the latest version of ESLint.
> chore(deps): update eslint to 9.27.0

- docs/rules/require-data-selectors.md
- lib/rules/require-data-selectors.js
- tests/lib/rules/require-data-selectors.js
This PR fixes (partially*)  #270 
- Fix that when selector as defined as variable and then used in `cy.get()`, no warning are being thrown. This is being done by first saving variable declaration of aliases or data selectors into a Map, and then when looking at `cy.get()` command it is also looking up potential use of variable in the map.
- Update test 
- Update doc 
*partially because cross-file declaration does not seems to be feasible, as ESlint only validate file by file.
> fix: dont throw warning on variable data selector

- eslint.config.mjs
- package-lock.json
- package.json
- PR https://github.com/cypress-io/eslint-plugin-cypress/pull/279 added a TypeScript declaration file `lib/flat.d.ts`
- The ESLint configuration [eslint.config.mjs](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/eslint.config.mjs) only lints JavaScript files
- Update ESLint-related `devDependencies` packages to latest versions
- Add `@eslint/js` explicitly
- Add [typescript](https://www.npmjs.com/package/typescript) and [typescript-eslint](https://www.npmjs.com/package/typescript-eslint) as `devDependencies` (see [typescript-eslint](https://typescript-eslint.io/) documentation)
- Expand [eslint.config.mjs](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/eslint.config.mjs) to lint `*.d.ts` and use recommended rules
```shell
npm ci
npm test
npm run …
```
> chore: lint TypeScript declaration files d.ts
